# Generated by Django 3.0.4 on 2020-03-26 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.FileField(blank=True, null=True, upload_to='avatar', verbose_name='Profile Photo')),
                ('username', models.CharField(max_length=50, verbose_name='Username')),
                ('name', models.CharField(max_length=40, verbose_name='Name')),
                ('surname', models.CharField(max_length=40, verbose_name='Surname')),
                ('about', models.TextField(max_length=1000, verbose_name='About')),
                ('rating', models.IntegerField(verbose_name='Rating')),
                ('email', models.EmailField(max_length=80, verbose_name='Email')),
                ('email_verified', models.DateTimeField(blank=True, null=True)),
                ('password', models.CharField(max_length=40, verbose_name='Password')),
                ('remember_token', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
